services:
  postgres:
    ports:
      - "5432:5432"

  backend:
    ports:
      - "8000:8000"
    command: >
      gunicorn
        --workers 4
        --worker-class uvicorn.workers.UvicornWorker
        --bind 0.0.0.0:8000
        app.main:app 

  frontend:
    ports:
      - "3000:3000"
    command: sh -c "pnpm install && pnpm build && pnpm start"
