services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_venv:/app/venv
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER-localhost}
      - POSTGRES_USER=${POSTGRES_USER-medpassadmin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-MPAdmin2025UNR}
      - POSTGRES_DB=${POSTGRES_DB-medpass}
      - SECRET_KEY=${SECRET_KEY-SUPERMOAGUSSUPERKEYMOGUS}

  frontend:
    build:
      context: ./medpass
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./medpass:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL-http://localhost:3000}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL-http://localhost:8000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET-SUPERMOAGUSSUPERKEYMOGUS}

volumes:
  backend_venv: