services:
  backend:
    volumes:
      - ./backend:/app           # live‑code mount
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    volumes:
      - ./medpass:/app          # live‑code mount
    command: pnpm dev
