name: Run Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt

    - name: Run database tests
      run: |
        cd backend
        python -m pytest app/tests/test_database.py -v
      env:
        POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

    - name: Run report tests
      run: |
        cd backend
        python -m pytest app/tests/test_report.py -v
      env:
        POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

    - name: Run risk tests
      run: |
        cd backend
        python -m pytest app/tests/test_risk.py -v
      env:
        POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}